// AUTO-GENERATED by web/scripts/derive-facts.mjs at prebuild.
// DO NOT EDIT — re-run `npm run prebuild` (or just `npm run build`) after changing the parent repo.
// To override at runtime, write the same shape to KV under key "facts:current".

export interface ProviderFact { id: string; label: string; env: string }

export interface RepoFacts {
  generatedAt: string;
  version: string | null;
  crates: string[];
  sandboxBackends: string[];
  providers: ProviderFact[];
  defaultModel: string | null;
  nodeEngines: string | null;
  toolCount: number | null;
  license: string | null;
  latestRelease: string | null;
}

export const FACTS: RepoFacts = {
  "generatedAt": "2026-05-14T19:43:39.727Z",
  "version": "0.8.37",
  "crates": [
    "agent",
    "app-server",
    "cli",
    "config",
    "core",
    "execpolicy",
    "hooks",
    "mcp",
    "protocol",
    "secrets",
    "state",
    "tools",
    "tui",
    "tui-core"
  ],
  "sandboxBackends": [
    "landlock (Linux)",
    "seatbelt (macOS)",
    "AppContainer / restricted tokens (Windows)"
  ],
  "providers": [
    {
      "id": "deepseek",
      "label": "DeepSeek",
      "env": "DEEPSEEK_API_KEY"
    },
    {
      "id": "nvidia-nim",
      "label": "NVIDIA NIM",
      "env": "NVIDIA_API_KEY"
    },
    {
      "id": "openai",
      "label": "OpenAI",
      "env": "OPENAI_API_KEY"
    },
    {
      "id": "openrouter",
      "label": "OpenRouter",
      "env": "OPENROUTER_API_KEY"
    },
    {
      "id": "novita",
      "label": "Novita",
      "env": "NOVITA_API_KEY"
    },
    {
      "id": "fireworks",
      "label": "Fireworks",
      "env": "FIREWORKS_API_KEY"
    },
    {
      "id": "sglang",
      "label": "sglang",
      "env": "SGLANG_API_KEY"
    },
    {
      "id": "vllm",
      "label": "vLLM",
      "env": "VLLM_API_KEY"
    },
    {
      "id": "ollama",
      "label": "Ollama",
      "env": "OLLAMA_API_KEY"
    }
  ],
  "defaultModel": "deepseek-v4-pro",
  "nodeEngines": ">=18",
  "toolCount": 68,
  "license": "MIT",
  "latestRelease": null
};
